# Uncomment the following lines to enable the Corne RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# Better compatibility with iPadOS
CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y

# Boost Bluetooth Transmission Power to max
# "the power consumption difference is negligible"
# https://zmk.dev/docs/troubleshooting#connectivity-issues
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

CONFIG_ZMK_KEYBOARD_NAME="Splitboard"
CONFIG_USB_DEVICE_MANUFACTURER="Mr. Splady LLC"

# Enable the Media-layer soft-off key.
CONFIG_ZMK_PM_SOFT_OFF=y

# Automatically deep-sleep after 10 minutes of inactivity on battery power.
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=600000

# Fetch the right-half battery level for the keyboard display,
# but only report the main left-half battery to connected hosts.
# https://github.com/zmkfirmware/zmk/pull/2045
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=n


# # # Enable ZMK Studio for Realtime Keymap Updates
# CONFIG_ZMK_STUDIO=y
# CONFIG_ZMK_STUDIO_LOCKING=n
